# Generated by Django 5.2.8 on 2025-11-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrazaMovimiento',
            fields=[
                ('id_traza', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('READ', 'Consultar'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PERMISSION_DENIED', 'Acceso Denegado')], help_text='Tipo de acción realizada', max_length=20)),
                ('tabla_afectada', models.CharField(help_text='Nombre de la tabla/modelo afectado', max_length=100)),
                ('id_registro', models.IntegerField(help_text='ID del registro afectado')),
                ('cambios_anteriores', models.JSONField(blank=True, help_text='Valores anteriores (para UPDATE/DELETE)', null=True)),
                ('cambios_nuevos', models.JSONField(blank=True, help_text='Valores nuevos (para CREATE/UPDATE)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del cliente', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User Agent del navegador')),
                ('resultado', models.CharField(choices=[('SUCCESS', 'Exitoso'), ('FAILED', 'Fallido')], default='SUCCESS', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la acción')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Traza de Movimiento',
                'verbose_name_plural': 'Trazas de Movimiento',
                'db_table': 'traza_movimiento',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
