# Generated by Django 5.2.8 on 2025-11-15 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrazaMovimiento',
            fields=[
                ('id_traza', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_accion', models.CharField(max_length=50)),
                ('entidad_afectada', models.CharField(max_length=50)),
                ('registro_pk_afectado', models.IntegerField()),
                ('detalle_cambio', models.TextField()),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Traza de Movimiento',
                'verbose_name_plural': 'Trazas de Movimientos',
                'db_table': 'traza_movimiento',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
