# Generated by Django 5.2.8 on 2025-11-16 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trazamovimiento',
            name='fk_usuario',
            field=models.ForeignKey(db_column='fk_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazas_movimiento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trazamovimiento',
            index=models.Index(fields=['fk_usuario', '-fecha_hora'], name='traza_movim_fk_usua_bce004_idx'),
        ),
        migrations.AddIndex(
            model_name='trazamovimiento',
            index=models.Index(fields=['tabla_afectada', '-fecha_hora'], name='traza_movim_tabla_a_b1d8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='trazamovimiento',
            index=models.Index(fields=['tipo_accion', '-fecha_hora'], name='traza_movim_tipo_ac_2336cc_idx'),
        ),
    ]
