# Generated by Django 5.2.8 on 2025-11-15 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_permiso', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permiso',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=15, unique=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fk_rol', models.ForeignKey(db_column='fk_rol', on_delete=django.db.models.deletion.PROTECT, to='core.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_permiso', models.ForeignKey(db_column='fk_permiso', on_delete=django.db.models.deletion.CASCADE, to='core.permiso')),
                ('fk_rol', models.ForeignKey(db_column='fk_rol', on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
            options={
                'verbose_name': 'Rol-Permiso',
                'verbose_name_plural': 'Roles-Permisos',
                'db_table': 'rol_permiso',
                'unique_together': {('fk_rol', 'fk_permiso')},
            },
        ),
    ]
