# Generated by Django 5.2.8 on 2025-11-16 18:01

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(choices=[('matrona_clinica', 'Matrona Clínica'), ('supervisor_jefe', 'Supervisor/Jefe de Área'), ('medico', 'Médico(a)'), ('enfermero', 'Enfermero(a)'), ('administrativo', 'Administrativo(a)')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del rol y responsabilidades')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
                'ordering': ['nombre_rol'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=15, unique=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('fk_rol', models.ForeignKey(blank=True, db_column='fk_rol', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', core.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_permiso', models.CharField(help_text='Código único del permiso ej: maternity:mother:create', max_length=100, unique=True)),
                ('nombre_permiso', models.CharField(help_text='Nombre legible del permiso', max_length=150)),
                ('descripcion', models.TextField(help_text='Descripción detallada del permiso')),
                ('categoria', models.CharField(choices=[('catalog', 'Catálogos'), ('maternity', 'Maternidad'), ('neonatology', 'Neonatología'), ('reports', 'Reportes'), ('alerts', 'Alertas'), ('compliance', 'Cumplimiento'), ('core', 'Core/Usuarios')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permiso',
                'ordering': ['categoria', 'codigo_permiso'],
                'indexes': [models.Index(fields=['codigo_permiso'], name='permiso_codigo__db951d_idx'), models.Index(fields=['categoria'], name='permiso_categor_e659af_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestriccionTurno',
            fields=[
                ('id_restriccion', models.AutoField(primary_key=True, serialize=False)),
                ('turno', models.CharField(choices=[('MATUTINO', 'Turno Matutino (08:00-16:00)'), ('VESPERTINO', 'Turno Vespertino (16:00-00:00)'), ('NOCTURNO', 'Turno Nocturno (00:00-08:00)')], help_text='Turno asignado a la matrona', max_length=20)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del turno')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de fin del turno (null = indefinido)', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fk_matrona', models.OneToOneField(db_column='fk_matrona', limit_choices_to={'fk_rol__nombre_rol': 'matrona_clinica'}, on_delete=django.db.models.deletion.CASCADE, related_name='restriccion_turno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restricción de Turno',
                'verbose_name_plural': 'Restricciones de Turno',
                'db_table': 'restriccion_turno',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fk_permiso', models.ForeignKey(db_column='fk_permiso', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.permiso')),
                ('fk_rol', models.ForeignKey(db_column='fk_rol', on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='core.rol')),
            ],
            options={
                'verbose_name': 'Rol-Permiso',
                'verbose_name_plural': 'Roles-Permisos',
                'db_table': 'rol_permiso',
                'ordering': ['fk_rol', 'fk_permiso'],
                'unique_together': {('fk_rol', 'fk_permiso')},
            },
        ),
    ]
