# Generated by Django 5.2.8 on 2025-11-15 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltaAnticonceptivo',
            fields=[
                ('id_alta_ac', models.AutoField(primary_key=True, serialize=False)),
                ('fk_evento', models.IntegerField()),
                ('tipo_alta', models.CharField(max_length=20)),
                ('fk_metodo_anticonceptivo', models.IntegerField(blank=True, null=True)),
                ('esterilizacion_quirurgica', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Alta con Anticonceptivo',
                'verbose_name_plural': 'Altas con Anticonceptivo',
                'db_table': 'alta_anticonceptivo',
            },
        ),
        migrations.CreateModel(
            name='IVEAtencion',
            fields=[
                ('id_ive_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('fk_causal', models.CharField(max_length=10)),
                ('edad_gestacional_semanas', models.IntegerField()),
                ('fk_voluntad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Atención IVE',
                'verbose_name_plural': 'Atenciones IVE',
                'db_table': 'ive_atencion',
            },
        ),
        migrations.CreateModel(
            name='IVEAcompanamiento',
            fields=[
                ('id_acomp_ive', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_profesional', models.CharField(max_length=50)),
                ('fk_ive_atencion', models.ForeignKey(db_column='fk_ive_atencion', on_delete=django.db.models.deletion.CASCADE, to='maternity.iveatencion')),
            ],
            options={
                'verbose_name': 'Acompañamiento IVE',
                'verbose_name_plural': 'Acompañamientos IVE',
                'db_table': 'ive_acompanamiento',
            },
        ),
        migrations.CreateModel(
            name='MadrePaciente',
            fields=[
                ('id_madre', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('discapacidad_senadis', models.BooleanField(default=False)),
                ('privada_de_libertad', models.BooleanField(default=False)),
                ('trans_masculino_no_binarie', models.BooleanField(default=False)),
                ('fk_nacionalidad', models.ForeignKey(db_column='fk_nacionalidad', on_delete=django.db.models.deletion.PROTECT, to='catalogs.catnacionalidad')),
                ('fk_pueblo_originario', models.ForeignKey(blank=True, db_column='fk_pueblo_originario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.catpueblooriginario')),
            ],
            options={
                'verbose_name': 'Madre Paciente',
                'verbose_name_plural': 'Madres Pacientes',
                'db_table': 'madre_paciente',
            },
        ),
        migrations.AddField(
            model_name='iveatencion',
            name='fk_madre',
            field=models.ForeignKey(db_column='fk_madre', on_delete=django.db.models.deletion.CASCADE, to='maternity.madrepaciente'),
        ),
        migrations.CreateModel(
            name='Embarazo',
            fields=[
                ('id_embarazo', models.AutoField(primary_key=True, serialize=False)),
                ('paridad', models.IntegerField()),
                ('control_prenatal', models.BooleanField(default=True)),
                ('semana_obstetrica', models.IntegerField()),
                ('riesgo_obstetrico', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_madre', models.ForeignKey(db_column='fk_madre', on_delete=django.db.models.deletion.CASCADE, to='maternity.madrepaciente')),
            ],
            options={
                'verbose_name': 'Embarazo',
                'verbose_name_plural': 'Embarazos',
                'db_table': 'embarazo',
            },
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id_parto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_parto', models.DateTimeField()),
                ('es_parto_multiple', models.BooleanField(default=False)),
                ('plan_de_parto', models.BooleanField(default=False)),
                ('fk_origen_ingreso', models.CharField(blank=True, max_length=50, null=True)),
                ('libertad_movimiento', models.BooleanField(default=False)),
                ('fk_posicion_parto', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_estado_perine', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_acompanante', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_sala_duelo_perinatal', models.BooleanField(default=False)),
                ('fk_clasificacion_robson', models.ForeignKey(blank=True, db_column='fk_clasificacion_robson', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogs.catrobson')),
                ('fk_madre', models.ForeignKey(db_column='fk_madre', on_delete=django.db.models.deletion.CASCADE, to='maternity.madrepaciente')),
                ('fk_profesional_responsable', models.ForeignKey(db_column='fk_profesional_responsable', on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
                ('fk_tipo_parto', models.ForeignKey(db_column='fk_tipo_parto', on_delete=django.db.models.deletion.PROTECT, to='catalogs.cattipoparto')),
            ],
            options={
                'verbose_name': 'Parto',
                'verbose_name_plural': 'Partos',
                'db_table': 'parto',
            },
        ),
        migrations.CreateModel(
            name='PartoAnestesia',
            fields=[
                ('id_anestesia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_anestesia', models.CharField(max_length=50)),
                ('solicitada_por_paciente', models.BooleanField(default=False)),
                ('fk_parto', models.ForeignKey(db_column='fk_parto', on_delete=django.db.models.deletion.CASCADE, to='maternity.parto')),
            ],
            options={
                'verbose_name': 'Anestesia de Parto',
                'verbose_name_plural': 'Anestesias de Parto',
                'db_table': 'parto_anestesia',
            },
        ),
        migrations.CreateModel(
            name='PartoComplicacion',
            fields=[
                ('id_parto_complicacion', models.AutoField(primary_key=True, serialize=False)),
                ('fk_causa_hpp', models.CharField(blank=True, max_length=50, null=True)),
                ('histerectomia_obstetrica', models.BooleanField(default=False)),
                ('transfusion_sanguinea', models.BooleanField(default=False)),
                ('fk_complicacion', models.ForeignKey(db_column='fk_complicacion', on_delete=django.db.models.deletion.PROTECT, to='catalogs.catcomplicacionparto')),
                ('fk_parto', models.ForeignKey(db_column='fk_parto', on_delete=django.db.models.deletion.CASCADE, to='maternity.parto')),
            ],
            options={
                'verbose_name': 'Complicación de Parto',
                'verbose_name_plural': 'Complicaciones de Parto',
                'db_table': 'parto_complicacion',
            },
        ),
    ]
