# Generated by Django 5.2.8 on 2025-11-16 18:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AltaAnticonceptivo',
            fields=[
                ('id_alta_ac', models.AutoField(primary_key=True, serialize=False)),
                ('fk_evento', models.IntegerField(help_text='ID del evento (parto o IVE)')),
                ('tipo_alta', models.CharField(choices=[('parto', 'Alta por parto'), ('ive', 'Alta por IVE'), ('otro', 'Otro motivo')], max_length=20)),
                ('fk_metodo_anticonceptivo', models.CharField(blank=True, choices=[('1', 'DIU'), ('2', 'Implante subdérmico'), ('3', 'Esterilización quirúrgica'), ('4', 'Métodos hormonales'), ('5', 'Otro')], help_text='Método anticonceptivo entregado', max_length=1, null=True)),
                ('esterilizacion_quirurgica', models.BooleanField(default=False, help_text='¿Se realizó esterilización quirúrgica?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alta con Anticonceptivo',
                'verbose_name_plural': 'Altas con Anticonceptivo',
                'db_table': 'alta_anticonceptivo',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='IVEAtencion',
            fields=[
                ('id_ive_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('fk_causal', models.CharField(choices=[('1', 'Violación o incesto'), ('2', 'Peligro para la vida o salud'), ('3', 'Inviabilidad fetal')], help_text='Causal de IVE', max_length=10)),
                ('edad_gestacional_semanas', models.IntegerField(help_text='Edad gestacional en semanas')),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Atención IVE',
                'verbose_name_plural': 'Atenciones IVE',
                'db_table': 'ive_atencion',
                'ordering': ['-fecha_atencion'],
            },
        ),
        migrations.CreateModel(
            name='IVEAcompanamiento',
            fields=[
                ('id_acomp_ive', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_profesional', models.CharField(choices=[('medico', 'Médico'), ('psicologo', 'Psicólogo'), ('asistente_social', 'Asistente Social'), ('matrona', 'Matrona'), ('otro', 'Otro')], max_length=50)),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True)),
                ('fk_ive_atencion', models.ForeignKey(db_column='fk_ive_atencion', on_delete=django.db.models.deletion.CASCADE, related_name='acompañamientos', to='maternity.iveatencion')),
            ],
            options={
                'verbose_name': 'Acompañamiento IVE',
                'verbose_name_plural': 'Acompañamientos IVE',
                'db_table': 'ive_acompanamiento',
            },
        ),
        migrations.CreateModel(
            name='MadrePaciente',
            fields=[
                ('id_madre', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(help_text='RUT de la madre (ej: 12345678-9)', max_length=15, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la madre', max_length=50)),
                ('apellido_paterno', models.CharField(help_text='Apellido paterno', max_length=50)),
                ('apellido_materno', models.CharField(help_text='Apellido materno', max_length=50)),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento de la madre')),
                ('discapacidad_senadis', models.BooleanField(default=False, help_text='Tiene discapacidad registrada en SENADIS')),
                ('privada_de_libertad', models.BooleanField(default=False, help_text='Está privada de libertad')),
                ('trans_masculino_no_binarie', models.BooleanField(default=False, help_text='Identidad de género diversa')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro en el sistema')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('fk_nacionalidad', models.ForeignKey(db_column='fk_nacionalidad', help_text='Nacionalidad', on_delete=django.db.models.deletion.PROTECT, to='catalogs.catnacionalidad')),
                ('fk_pueblo_originario', models.ForeignKey(blank=True, db_column='fk_pueblo_originario', help_text='Pueblo originario (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.catpueblooriginario')),
            ],
            options={
                'verbose_name': 'Madre Paciente',
                'verbose_name_plural': 'Madres Pacientes',
                'db_table': 'madre_paciente',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='iveatencion',
            name='fk_madre',
            field=models.ForeignKey(db_column='fk_madre', on_delete=django.db.models.deletion.CASCADE, related_name='ive_atenciones', to='maternity.madrepaciente'),
        ),
        migrations.CreateModel(
            name='Embarazo',
            fields=[
                ('id_embarazo', models.AutoField(primary_key=True, serialize=False)),
                ('paridad', models.IntegerField(help_text='Número de embarazos previos')),
                ('control_prenatal', models.BooleanField(default=True, help_text='¿Asistió a control prenatal?')),
                ('fecha_ultima_menstruacion', models.DateField(help_text='Fecha de última menstruación')),
                ('semana_obstetrica', models.IntegerField(help_text='Semana de gestación', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(42)])),
                ('riesgo_obstetrico', models.CharField(blank=True, help_text='Clasificación de riesgo', max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('fk_madre', models.ForeignKey(db_column='fk_madre', help_text='Madre paciente', on_delete=django.db.models.deletion.CASCADE, related_name='embarazos', to='maternity.madrepaciente')),
            ],
            options={
                'verbose_name': 'Embarazo',
                'verbose_name_plural': 'Embarazos',
                'db_table': 'embarazo',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id_parto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_parto', models.DateTimeField(help_text='Fecha y hora del parto')),
                ('es_parto_multiple', models.BooleanField(default=False, help_text='¿Es parto múltiple (gemelos, trillizos, etc)?')),
                ('plan_de_parto', models.BooleanField(default=False, help_text='¿Existe plan de parto?')),
                ('libertad_movimiento', models.BooleanField(default=False, help_text='¿Tuvo libertad de movimiento?')),
                ('horas_trabajo_parto', models.FloatField(default=0, help_text='Horas de trabajo de parto')),
                ('fk_acompanante', models.CharField(blank=True, help_text='Persona que acompaño el parto', max_length=100, null=True)),
                ('fk_sala_duelo_perinatal', models.BooleanField(default=False, help_text='¿Se utilizó sala de duelo perinatal?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('fk_clasificacion_robson', models.ForeignKey(blank=True, db_column='fk_clasificacion_robson', help_text='Clasificación de Robson', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogs.catrobson')),
                ('fk_madre', models.ForeignKey(db_column='fk_madre', help_text='Madre paciente', on_delete=django.db.models.deletion.CASCADE, related_name='partos', to='maternity.madrepaciente')),
                ('fk_profesional_responsable', models.ForeignKey(db_column='fk_profesional_responsable', help_text='Profesional responsable del parto', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fk_tipo_parto', models.ForeignKey(db_column='fk_tipo_parto', help_text='Tipo de parto', on_delete=django.db.models.deletion.PROTECT, to='catalogs.cattipoparto')),
            ],
            options={
                'verbose_name': 'Parto',
                'verbose_name_plural': 'Partos',
                'db_table': 'parto',
                'ordering': ['-fecha_parto'],
            },
        ),
        migrations.CreateModel(
            name='PartoAnestesia',
            fields=[
                ('id_anestesia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_anestesia', models.CharField(choices=[('ninguna', 'Sin anestesia'), ('local', 'Anestesia local'), ('epidural', 'Anestesia epidural'), ('raquídea', 'Anestesia raquídea'), ('general', 'Anestesia general'), ('otra', 'Otra')], max_length=50)),
                ('solicitada_por_paciente', models.BooleanField(default=False, help_text='¿Fue solicitada por la paciente?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fk_parto', models.ForeignKey(db_column='fk_parto', on_delete=django.db.models.deletion.CASCADE, related_name='anestesias', to='maternity.parto')),
            ],
            options={
                'verbose_name': 'Anestesia de Parto',
                'verbose_name_plural': 'Anestesias de Parto',
                'db_table': 'parto_anestesia',
            },
        ),
        migrations.CreateModel(
            name='PartoComplicacion',
            fields=[
                ('id_complicacion', models.AutoField(primary_key=True, serialize=False)),
                ('histerectomia_obstetrica', models.BooleanField(default=False, help_text='¿Se realizó histerectomía obstétrica?')),
                ('transfusion_sanguinea', models.BooleanField(default=False, help_text='¿Se realizó transfusión sanguínea?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro')),
                ('fk_complicacion', models.ForeignKey(db_column='fk_complicacion', help_text='Tipo de complicación', on_delete=django.db.models.deletion.PROTECT, to='catalogs.catcomplicacionparto')),
                ('fk_parto', models.ForeignKey(db_column='fk_parto', help_text='Parto asociado', on_delete=django.db.models.deletion.CASCADE, related_name='complicaciones', to='maternity.parto')),
            ],
            options={
                'verbose_name': 'Complicación de Parto',
                'verbose_name_plural': 'Complicaciones de Parto',
                'db_table': 'parto_complicacion',
            },
        ),
        migrations.AddIndex(
            model_name='madrepaciente',
            index=models.Index(fields=['run'], name='madre_pacie_run_3665fa_idx'),
        ),
        migrations.AddIndex(
            model_name='madrepaciente',
            index=models.Index(fields=['nombre', 'apellido_paterno'], name='madre_pacie_nombre_5d1b66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='embarazo',
            unique_together={('fk_madre', 'fecha_ultima_menstruacion')},
        ),
        migrations.AddIndex(
            model_name='partocomplicacion',
            index=models.Index(fields=['fk_parto'], name='parto_compl_fk_part_827689_idx'),
        ),
        migrations.AddIndex(
            model_name='partocomplicacion',
            index=models.Index(fields=['fecha_registro'], name='parto_compl_fecha_r_beea03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partocomplicacion',
            unique_together={('fk_parto', 'fk_complicacion')},
        ),
    ]
