# Generated by Django 5.2.8 on 2025-11-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatComplicacionParto',
            fields=[
                ('id_complicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Complicación de Parto',
                'verbose_name_plural': 'Complicaciones de Parto',
                'db_table': 'cat_complicacion_parto',
            },
        ),
        migrations.CreateModel(
            name='CatNacionalidad',
            fields=[
                ('id_nacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
                'db_table': 'cat_nacionalidad',
            },
        ),
        migrations.CreateModel(
            name='CatPuebloOriginario',
            fields=[
                ('id_pueblo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pueblo Originario',
                'verbose_name_plural': 'Pueblos Originarios',
                'db_table': 'cat_pueblo_originario',
            },
        ),
        migrations.CreateModel(
            name='CatRobson',
            fields=[
                ('id_robson', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Clasificación Robson',
                'verbose_name_plural': 'Clasificaciones Robson',
                'db_table': 'cat_robson',
            },
        ),
        migrations.CreateModel(
            name='CatTipoParto',
            fields=[
                ('id_tipo_parto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Parto',
                'verbose_name_plural': 'Tipos de Parto',
                'db_table': 'cat_tipo_parto',
            },
        ),
    ]
