# Generated by Django 5.2.8 on 2025-11-16 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteREM',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_reporte', models.CharField(max_length=50)),
                ('rango_fecha_inicio', models.DateField()),
                ('rango_fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('fk_usuario_genera', models.ForeignKey(db_column='fk_usuario_genera', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte REM',
                'verbose_name_plural': 'Reportes REM',
                'db_table': 'reporte_rem',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='ReporteREMDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_variable_rem', models.CharField(max_length=100)),
                ('valor_reportado', models.IntegerField()),
                ('fk_reporte', models.ForeignKey(db_column='fk_reporte', on_delete=django.db.models.deletion.CASCADE, to='reports.reporterem')),
            ],
            options={
                'verbose_name': 'Detalle Reporte REM',
                'verbose_name_plural': 'Detalles Reportes REM',
                'db_table': 'reporte_rem_detalle',
                'unique_together': {('fk_reporte', 'nombre_variable_rem')},
            },
        ),
    ]
