"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    
    # Local apps
    'core',
    'catalogs',
    'maternity',
    'neonatology',
    'compliance',
    'alerts',
    'reports',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.AuditoriaMiddleware',  # Middleware de auditoría
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.mysql'),
        'NAME': config('DB_NAME', default='hospital_maternity_system'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom user model
AUTH_USER_MODEL = 'core.Usuario'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    # ← AGREGAR ESTA LÍNEA
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id_usuario',
    'USER_ID_CLAIM': 'user_id',
    'JTI_CLAIM': 'jti',
}

# CORS
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=False, cast=bool)


# ============================================
# SPECTACULAR SETTINGS - Nueva sección
# ============================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'Hospital Maternity System API',
    'DESCRIPTION': """
    Sistema de gestión hospitalaria para el registro y seguimiento de partos, 
    recién nacidos y generación de reportes REM (Reporte Estadístico Mensual).
    
    ## Características principales:
    - **Autenticación JWT** con tokens de acceso y refresh
    - **Sistema RBAC** (Role-Based Access Control) con 5 roles y 24 permisos
    - **Gestión de Maternidad**: Madres, embarazos, partos, IVE
    - **Gestión de Neonatología**: Recién nacidos, tamizajes, egresos
    - **Auditoría completa** de todas las acciones
    - **Reportes REM** automatizados
    
    ## Roles del sistema:
    - **Matrona Clínica**: Registro de partos y RN (con restricción de turno)
    - **Supervisor/Jefe**: Acceso completo y gestión de reportes
    - **Médico(a)**: Consulta clínica y gestión de complicaciones
    - **Enfermero(a)**: Registro de procedimientos y tamizajes
    - **Administrativo(a)**: Gestión de ingresos y altas
    
    ## Autenticación:
    1. Obtener tokens: `POST /api/auth/token/` con `run` y `password`
    2. Usar el access token en header: `Authorization: Bearer {token}`
    3. Refrescar token: `POST /api/auth/token/refresh/` con el refresh token
    """,
    'VERSION': '2.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    
    # Información de contacto y licencia
    'CONTACT': {
        'name': 'Equipo de Desarrollo',
        'email': 'dev@hospital.com',
    },
    'LICENSE': {
        'name': 'Privado - Todos los derechos reservados',
    },
    
    # Configuración de seguridad (JWT)
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
        }
    },
    'SECURITY': [{'Bearer': []}],
    
    # Configuración de tags (agrupación en la UI)
    'TAGS': [
        {'name': 'Auth', 'description': 'Autenticación y gestión de tokens JWT'},
        {'name': 'Usuarios', 'description': 'Gestión de usuarios y perfiles'},
        {'name': 'Roles & Permisos', 'description': 'Sistema RBAC: roles, permisos y asignaciones'},
        {'name': 'Catálogos', 'description': 'Listas estandarizadas (nacionalidades, tipos de parto, etc.)'},
        {'name': 'Maternidad', 'description': 'Gestión de madres, embarazos, partos e IVE'},
        {'name': 'Neonatología', 'description': 'Gestión de recién nacidos, tamizajes y egresos'},
        {'name': 'Auditoría', 'description': 'Trazabilidad de acciones del sistema'},
        {'name': 'Alertas', 'description': 'Sistema de alertas y notificaciones'},
        {'name': 'Reportes', 'description': 'Generación de reportes REM'},
    ],
    
    # Configuración de componentes
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_NO_READ_ONLY_REQUIRED': True,
    
    # Configuración de Swagger UI
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
        'tryItOutEnabled': True,
        'syntaxHighlight.theme': 'monokai',
    },
    
    # Configuración de ReDoc
    'REDOC_UI_SETTINGS': {
        'hideDownloadButton': False,
        'expandResponses': '200,201',
        'pathInMiddlePanel': True,
    },
    
    # Ordenamiento de endpoints
    'SORT_OPERATIONS': True,
    'SORT_OPERATION_PARAMETERS': True,
}