# Generated by Django 5.2.8 on 2025-11-16 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maternity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id_rn', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=10)),
                ('peso_gramos', models.IntegerField()),
                ('talla_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('anomalia_congenita', models.BooleanField(default=False)),
                ('tipo_muerte', models.CharField(blank=True, max_length=20, null=True)),
                ('fk_parto', models.ForeignKey(db_column='fk_parto', on_delete=django.db.models.deletion.CASCADE, to='maternity.parto')),
            ],
            options={
                'verbose_name': 'Recién Nacido',
                'verbose_name_plural': 'Recién Nacidos',
                'db_table': 'recien_nacido',
            },
        ),
        migrations.CreateModel(
            name='RNEgreso',
            fields=[
                ('fk_rn', models.OneToOneField(db_column='fk_rn', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='neonatology.reciennacido')),
                ('tipo_alimentacion_alta', models.CharField(max_length=50)),
                ('motivo_no_lme', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Egreso RN',
                'verbose_name_plural': 'Egresos RN',
                'db_table': 'rn_egreso',
            },
        ),
        migrations.CreateModel(
            name='RNTamizajeAuditivo',
            fields=[
                ('id_tamizaje_auditivo', models.AutoField(primary_key=True, serialize=False)),
                ('oido_derecho_resultado', models.CharField(max_length=10)),
                ('oido_izquierdo_resultado', models.CharField(max_length=10)),
                ('es_retamizaje', models.BooleanField(default=False)),
                ('es_ambulatorio', models.BooleanField(default=False)),
                ('fk_rn', models.ForeignKey(db_column='fk_rn', on_delete=django.db.models.deletion.CASCADE, to='neonatology.reciennacido')),
            ],
            options={
                'verbose_name': 'Tamizaje Auditivo RN',
                'verbose_name_plural': 'Tamizajes Auditivos RN',
                'db_table': 'rn_tamizaje_auditivo',
            },
        ),
        migrations.CreateModel(
            name='RNTamizajeCardiopatia',
            fields=[
                ('id_tamizaje_cardiopatia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_tamizaje', models.DateTimeField()),
                ('saturacion_mano_derecha', models.IntegerField()),
                ('saturacion_pie', models.IntegerField()),
                ('referido_cardiologia', models.BooleanField(default=False)),
                ('fk_rn', models.ForeignKey(db_column='fk_rn', on_delete=django.db.models.deletion.CASCADE, to='neonatology.reciennacido')),
            ],
            options={
                'verbose_name': 'Tamizaje Cardiopatía RN',
                'verbose_name_plural': 'Tamizajes Cardiopatías RN',
                'db_table': 'rn_tamizaje_cardiopatia',
            },
        ),
        migrations.CreateModel(
            name='RNTamizajeMetabolico',
            fields=[
                ('id_tamizaje_metabolico', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_muestra', models.DateField()),
                ('es_segunda_muestra', models.BooleanField(default=False)),
                ('resultado_alterado', models.BooleanField(default=False)),
                ('fk_rn', models.ForeignKey(db_column='fk_rn', on_delete=django.db.models.deletion.CASCADE, to='neonatology.reciennacido')),
            ],
            options={
                'verbose_name': 'Tamizaje Metabólico RN',
                'verbose_name_plural': 'Tamizajes Metabólicos RN',
                'db_table': 'rn_tamizaje_metabolico',
            },
        ),
        migrations.CreateModel(
            name='RNAtencionInmediata',
            fields=[
                ('fk_rn', models.OneToOneField(db_column='fk_rn', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='neonatology.reciennacido')),
                ('apgar_1_minuto', models.IntegerField()),
                ('apgar_5_minutos', models.IntegerField()),
                ('ligadura_tardia_cordon', models.BooleanField(default=False)),
                ('contacto_piel_piel', models.CharField(blank=True, max_length=50, null=True)),
                ('profilaxis_hepatitis_b', models.BooleanField(default=False)),
                ('profilaxis_ocular', models.BooleanField(default=False)),
                ('reanimacion_basica', models.BooleanField(default=False)),
                ('reanimacion_avanzada', models.BooleanField(default=False)),
                ('fk_profesional_registra', models.ForeignKey(db_column='fk_profesional_registra', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atención Inmediata RN',
                'verbose_name_plural': 'Atenciones Inmediatas RN',
                'db_table': 'rn_atencion_inmediata',
            },
        ),
    ]
