# Generated by Django 5.2.8 on 2025-11-15 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSistema',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_alerta', models.CharField(max_length=50)),
                ('nivel_gravedad', models.CharField(max_length=10)),
                ('entidad_origen', models.CharField(max_length=50)),
                ('resuelto', models.BooleanField(default=False)),
                ('fk_usuario_genera', models.ForeignKey(db_column='fk_usuario_genera', on_delete=django.db.models.deletion.PROTECT, related_name='alertas_generadas', to='core.usuario')),
                ('fk_usuario_resuelve', models.ForeignKey(blank=True, db_column='fk_usuario_resuelve', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Alerta del Sistema',
                'verbose_name_plural': 'Alertas del Sistema',
                'db_table': 'alerta_sistema',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
