# Generated by Django 5.2.8 on 2025-11-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSistema',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_alerta', models.CharField(max_length=50)),
                ('nivel_gravedad', models.CharField(max_length=10)),
                ('entidad_origen', models.CharField(max_length=50)),
                ('resuelto', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Alerta del Sistema',
                'verbose_name_plural': 'Alertas del Sistema',
                'db_table': 'alerta_sistema',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
