# Generated by Django 5.2.8 on 2025-11-16 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertasistema',
            name='fk_usuario_genera',
            field=models.ForeignKey(db_column='fk_usuario_genera', on_delete=django.db.models.deletion.PROTECT, related_name='alertas_generadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='fk_usuario_resuelve',
            field=models.ForeignKey(blank=True, db_column='fk_usuario_resuelve', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL),
        ),
    ]
