# Generated by Django 5.2.8 on 2025-12-02 00:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FioriAppCategory',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la categoría', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción de la categoría')),
                ('icon', models.CharField(default='folder', help_text="Icono UI5 (ej: 'folder', 'group')", max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Aplicación Fiori',
                'verbose_name_plural': 'Categorías de Aplicaciones Fiori',
                'db_table': 'fiori_app_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FioriGroup',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del grupo', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='group', help_text='Icono del grupo', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, help_text='¿Está activo el grupo?')),
                ('is_collapsible', models.BooleanField(default=True, help_text='¿Se puede colapsar el grupo?')),
                ('collapsed_by_default', models.BooleanField(default=False, help_text='¿Está colapsado por defecto?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo de Aplicaciones Fiori',
                'verbose_name_plural': 'Grupos de Aplicaciones Fiori',
                'db_table': 'fiori_group',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserFioriPreferences',
            fields=[
                ('user', models.OneToOneField(db_column='fk_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fiori_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('theme', models.CharField(choices=[('sap_horizon', 'SAP Horizon'), ('sap_fiori_3', 'SAP Fiori 3'), ('sap_belize', 'SAP Belize')], default='sap_horizon', help_text='Tema visual del FLP', max_length=20)),
                ('tile_size_preference', models.CharField(choices=[('1x1', '1x1'), ('1x2', '1x2'), ('2x2', '2x2')], default='1x1', help_text='Tamaño preferido de tiles', max_length=5)),
                ('compact_mode', models.BooleanField(default=False, help_text='Modo compacto (más tiles por fila)')),
                ('group_by_category', models.BooleanField(default=True, help_text='Agrupar apps por categoría')),
                ('show_recent_apps', models.BooleanField(default=True, help_text='Mostrar sección de apps recientes')),
                ('recent_apps_count', models.IntegerField(default=5, help_text='Cantidad de apps recientes a mostrar', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)])),
                ('enable_notifications', models.BooleanField(default=True, help_text='Habilitar notificaciones')),
                ('notification_sound', models.BooleanField(default=False, help_text='Sonido en notificaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preferencias Fiori del Usuario',
                'verbose_name_plural': 'Preferencias Fiori de Usuarios',
                'db_table': 'user_fiori_preferences',
            },
        ),
        migrations.CreateModel(
            name='FioriApp',
            fields=[
                ('id_app', models.AutoField(primary_key=True, serialize=False)),
                ('app_id', models.CharField(help_text="ID único de la app (ej: 'madres-list', 'partos-create')", max_length=100, unique=True)),
                ('title', models.CharField(help_text='Título de la aplicación', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='Subtítulo descriptivo', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción completa de la app')),
                ('icon', models.CharField(default='activity-items', help_text="Icono SAP UI5 (ej: 'patient', 'clinical-order', 'doctor')", max_length=50)),
                ('tile_type', models.CharField(choices=[('standard', 'Standard Tile'), ('feed', 'Feed Tile'), ('numeric', 'Numeric Content'), ('link', 'Link Tile')], default='standard', help_text='Tipo de tile', max_length=20)),
                ('tile_size', models.CharField(choices=[('1x1', '1x1'), ('1x2', '1x2'), ('2x2', '2x2')], default='1x1', help_text='Tamaño del tile', max_length=5)),
                ('background_color', models.CharField(default='Accent6', help_text="Color de fondo SAP (ej: 'Accent1', 'Accent6', 'Neutral')", max_length=20)),
                ('url_path', models.CharField(help_text="Ruta URL de la app (ej: '/fiori/madres/list/')", max_length=200)),
                ('module_name', models.CharField(help_text="Nombre del módulo Python (ej: 'fiori.madres')", max_length=100)),
                ('required_permissions', models.JSONField(blank=True, default=list, help_text="Lista de permisos requeridos ['app.perm1', 'app.perm2']")),
                ('is_transactional', models.BooleanField(default=True, help_text='¿Es una app transaccional o analítica?')),
                ('is_mobile_ready', models.BooleanField(default=True, help_text='¿Está optimizada para móviles?')),
                ('default_order', models.IntegerField(default=0, help_text='Orden predeterminado en el FLP')),
                ('active', models.BooleanField(default=True, help_text='¿Está activa la aplicación?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Grupos (roles) que pueden acceder', related_name='fiori_apps', to='auth.group')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fiori_apps', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Categoría de la aplicación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='fiori.fioriappcategory')),
            ],
            options={
                'verbose_name': 'Aplicación Fiori',
                'verbose_name_plural': 'Aplicaciones Fiori',
                'db_table': 'fiori_app',
                'ordering': ['default_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FioriGroupApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiori.fioriapp')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiori.fiorigroup')),
            ],
            options={
                'db_table': 'fiori_group_app',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='fiorigroup',
            name='apps',
            field=models.ManyToManyField(related_name='groups', through='fiori.FioriGroupApp', to='fiori.fioriapp'),
        ),
        migrations.CreateModel(
            name='LaunchpadSettings',
            fields=[
                ('user', models.OneToOneField(db_column='fk_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='launchpad_settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('theme', models.CharField(choices=[('sap_fiori_3', 'SAP Fiori 3'), ('sap_horizon', 'SAP Horizon'), ('sap_belize', 'SAP Belize')], default='sap_fiori_3', help_text='Tema visual del Launchpad', max_length=20)),
                ('view_mode', models.CharField(choices=[('comfortable', 'Comfortable'), ('cozy', 'Cozy'), ('compact', 'Compact')], default='comfortable', help_text='Modo de vista del Launchpad', max_length=20)),
                ('show_groups', models.BooleanField(default=True, help_text='¿Mostrar grupos de aplicaciones?')),
                ('tiles_per_row', models.IntegerField(default=4, help_text='Cantidad de tiles por fila', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_app', models.ForeignKey(blank=True, help_text='Aplicación predeterminada al iniciar sesión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='fiori.fioriapp')),
            ],
            options={
                'verbose_name': 'Configuración del Launchpad',
                'verbose_name_plural': 'Configuraciones del Launchpad',
                'db_table': 'launchpad_settings',
            },
        ),
        migrations.CreateModel(
            name='UserAppConfig',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('is_visible', models.BooleanField(default=True, help_text='¿Está visible en el FLP del usuario?')),
                ('custom_order', models.IntegerField(default=0, help_text='Orden personalizado por el usuario')),
                ('is_favorite', models.BooleanField(default=False, help_text='¿Está marcada como favorita?')),
                ('custom_group_name', models.CharField(blank=True, help_text='Nombre de grupo personalizado (opcional)', max_length=100)),
                ('access_count', models.IntegerField(default=0, help_text='Cantidad de veces que accedió')),
                ('last_accessed', models.DateTimeField(blank=True, help_text='Última vez que accedió', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(db_column='fk_app', on_delete=django.db.models.deletion.CASCADE, related_name='user_configs', to='fiori.fioriapp')),
                ('user', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='app_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de App por Usuario',
                'verbose_name_plural': 'Configuraciones de Apps por Usuario',
                'db_table': 'user_app_config',
                'ordering': ['custom_order', 'app__title'],
            },
        ),
        migrations.AddIndex(
            model_name='fioriapp',
            index=models.Index(fields=['app_id'], name='fiori_app_app_id_db2fad_idx'),
        ),
        migrations.AddIndex(
            model_name='fioriapp',
            index=models.Index(fields=['active', 'default_order'], name='fiori_app_active_3bbb66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fiorigroupapp',
            unique_together={('group', 'app')},
        ),
        migrations.AddIndex(
            model_name='userappconfig',
            index=models.Index(fields=['user', 'is_visible'], name='user_app_co_fk_usua_9bc33c_idx'),
        ),
        migrations.AddIndex(
            model_name='userappconfig',
            index=models.Index(fields=['user', 'custom_order'], name='user_app_co_fk_usua_580dec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userappconfig',
            unique_together={('user', 'app')},
        ),
    ]
